name: CI

on:
  push:
    branches: [ main, deploy ]
  pull_request:
    branches: [ main, deploy ]

jobs:
  test:
    uses: ./.github/workflows/test-reusable.yml
    with:
      os: 'matrix'

  format-check:
    uses: ./.github/workflows/format-check-reusable.yml
